spring:
  datasource:
    name: monkeyqi
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true&allowPublicKeyRetrieval=true
    username: root
    password: sw3377549
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # 连接超时时间 （毫秒）
    timeout: 10000ms
    password: sw3377549
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        max-wait: -1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #      naming:
  #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #    mvc:
  #      view:
  #        prefix: classpath:/templates/html/
  #        suffix: .html

#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java

server:
  port: 443
#  port: 8080
  servlet.context-path: /community
  tomcat:
    uri-encoding: utf-8
  ssl:
    key-store: classpath:3791279_nuandao.zhouxy.xyz.pfx
    key-store-password: q7lI293r
    key-store-type: PKCS12
logging:
  level:
    com.support.mapper: debug
    root:  info
#debug: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.support.pojo.view
  configuration:
    map-underscore-to-camel-case: true

